"""rename user field 'project' to 'projects'

Revision ID: 137416d523a3
Revises: 2f88eafa7051
Create Date: 2025-01-07 13:33:07.812618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '137416d523a3'
down_revision: Union[str, None] = '2f88eafa7051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('projects', sa.ARRAY(sa.String()), nullable=True))
    op.drop_index('user_project_idx', table_name='user_table')
    op.create_index('user_projects_idx', 'user_table', ['projects'], unique=False)
    op.drop_column('user_table', 'project')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('project', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_index('user_projects_idx', table_name='user_table')
    op.create_index('user_project_idx', 'user_table', ['project'], unique=False)
    op.drop_column('user_table', 'projects')
    # ### end Alembic commands ###
