"""new field for user table 'project' and some indexes

Revision ID: 2f88eafa7051
Revises: f808babdebe0
Create Date: 2025-01-07 13:09:22.238681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f88eafa7051'
down_revision: Union[str, None] = 'f808babdebe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('permission_ident_idx', 'permission_table', ['ident'], unique=False)
    op.create_index('permission_user_ident_idx', 'permission_table', ['user_ident'], unique=False)
    op.create_index('refresh_token_user_ident_idx', 'refresh_token_table', ['user_ident'], unique=False)
    op.add_column('user_table', sa.Column('project', sa.ARRAY(sa.String()), nullable=True))
    op.create_index('user_login_idx', 'user_table', ['login'], unique=False)
    op.create_index('user_project_idx', 'user_table', ['project'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_project_idx', table_name='user_table')
    op.drop_index('user_login_idx', table_name='user_table')
    op.drop_column('user_table', 'project')
    op.drop_index('refresh_token_user_ident_idx', table_name='refresh_token_table')
    op.drop_index('permission_user_ident_idx', table_name='permission_table')
    op.drop_index('permission_ident_idx', table_name='permission_table')
    # ### end Alembic commands ###
