"""permission table update

Revision ID: f808babdebe0
Revises: 9f541c455675
Create Date: 2024-12-04 15:08:47.360890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f808babdebe0'
down_revision: Union[str, None] = '9f541c455675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group_table')
    op.add_column('permission_table', sa.Column('is_super_user', sa.Boolean(), nullable=False))
    op.add_column('permission_table', sa.Column('personal_naks_certification_data_get', sa.Boolean(), nullable=False))
    op.add_column('permission_table', sa.Column('personal_naks_certification_data_create', sa.Boolean(), nullable=False))
    op.add_column('permission_table', sa.Column('personal_naks_certification_data_update', sa.Boolean(), nullable=False))
    op.add_column('permission_table', sa.Column('personal_naks_certification_data_delete', sa.Boolean(), nullable=False))
    op.add_column('permission_table', sa.Column('acst_data_get', sa.Boolean(), nullable=False))
    op.add_column('permission_table', sa.Column('acst_data_create', sa.Boolean(), nullable=False))
    op.add_column('permission_table', sa.Column('acst_data_update', sa.Boolean(), nullable=False))
    op.add_column('permission_table', sa.Column('acst_data_delete', sa.Boolean(), nullable=False))
    op.add_column('permission_table', sa.Column('acst_file_download', sa.Boolean(), nullable=False))
    op.add_column('permission_table', sa.Column('acst_file_upload', sa.Boolean(), nullable=False))
    op.add_column('permission_table', sa.Column('personal_naks_certification_file_download', sa.Boolean(), nullable=False))
    op.add_column('permission_table', sa.Column('personal_naks_certification_file_upload', sa.Boolean(), nullable=False))
    op.add_column('permission_table', sa.Column('personal_naks_protocol_file_download', sa.Boolean(), nullable=False))
    op.add_column('permission_table', sa.Column('personal_naks_protocol_file_upload', sa.Boolean(), nullable=False))
    op.drop_column('permission_table', 'personal_certification_data_get')
    op.drop_column('permission_table', 'personal_certification_data_delete')
    op.drop_column('permission_table', 'personal_certification_data_update')
    op.drop_column('permission_table', 'personal_certification_data_create')
    op.drop_column('user_table', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('permission_table', sa.Column('personal_certification_data_create', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('permission_table', sa.Column('personal_certification_data_update', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('permission_table', sa.Column('personal_certification_data_delete', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('permission_table', sa.Column('personal_certification_data_get', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('permission_table', 'personal_naks_protocol_file_upload')
    op.drop_column('permission_table', 'personal_naks_protocol_file_download')
    op.drop_column('permission_table', 'personal_naks_certification_file_upload')
    op.drop_column('permission_table', 'personal_naks_certification_file_download')
    op.drop_column('permission_table', 'acst_file_upload')
    op.drop_column('permission_table', 'acst_file_download')
    op.drop_column('permission_table', 'acst_data_delete')
    op.drop_column('permission_table', 'acst_data_update')
    op.drop_column('permission_table', 'acst_data_create')
    op.drop_column('permission_table', 'acst_data_get')
    op.drop_column('permission_table', 'personal_naks_certification_data_delete')
    op.drop_column('permission_table', 'personal_naks_certification_data_update')
    op.drop_column('permission_table', 'personal_naks_certification_data_create')
    op.drop_column('permission_table', 'personal_naks_certification_data_get')
    op.drop_column('permission_table', 'is_super_user')
    op.create_table('user_group_table',
    sa.Column('ident', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_ident', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_ident'], ['user_table.ident'], name='user_group_table_user_ident_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ident', name='user_group_table_pkey')
    )
    # ### end Alembic commands ###
