"""init migration

Revision ID: 14262e198076
Revises: 
Create Date: 2024-06-28 11:36:16.913185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14262e198076'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fki_user_refresh_token_fk', table_name='refresh_token_table')
    op.create_index('refresh_token_ident_idx', 'refresh_token_table', ['ident'], unique=False)
    op.create_index('revoked_idx', 'refresh_token_table', ['revoked'], unique=False)
    op.create_index('token_idx', 'refresh_token_table', ['token'], unique=False)
    op.drop_constraint('user_refresh_token_fk', 'refresh_token_table', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_token_table', 'user_table', ['user_ident'], ['ident'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('user_ident_idx', 'user_table', ['ident'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_ident_idx', table_name='user_table')
    op.drop_constraint(None, 'refresh_token_table', type_='foreignkey')
    op.create_foreign_key('user_refresh_token_fk', 'refresh_token_table', 'user_table', ['user_ident'], ['ident'])
    op.drop_index('token_idx', table_name='refresh_token_table')
    op.drop_index('revoked_idx', table_name='refresh_token_table')
    op.drop_index('refresh_token_ident_idx', table_name='refresh_token_table')
    op.create_index('fki_user_refresh_token_fk', 'refresh_token_table', ['user_ident'], unique=False)
    # ### end Alembic commands ###
