"""init migration

Revision ID: 34678c79c5e6
Revises: 
Create Date: 2024-07-22 14:59:40.688257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34678c79c5e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('ident', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('sign_dt', sa.DateTime(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.Column('login_dt', sa.DateTime(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ident'),
    sa.UniqueConstraint('login')
    )
    op.create_index('user_ident_idx', 'user_table', ['ident'], unique=False)
    op.create_table('permission_table',
    sa.Column('ident', sa.UUID(), nullable=False),
    sa.Column('user_ident', sa.UUID(), nullable=False),
    sa.Column('personal_data_get', sa.Boolean(), nullable=False),
    sa.Column('personal_data_create', sa.Boolean(), nullable=False),
    sa.Column('personal_data_update', sa.Boolean(), nullable=False),
    sa.Column('personal_data_delete', sa.Boolean(), nullable=False),
    sa.Column('personal_certification_data_get', sa.Boolean(), nullable=False),
    sa.Column('personal_certification_data_create', sa.Boolean(), nullable=False),
    sa.Column('personal_certification_data_update', sa.Boolean(), nullable=False),
    sa.Column('personal_certification_data_delete', sa.Boolean(), nullable=False),
    sa.Column('ndt_data_get', sa.Boolean(), nullable=False),
    sa.Column('ndt_data_create', sa.Boolean(), nullable=False),
    sa.Column('ndt_data_update', sa.Boolean(), nullable=False),
    sa.Column('ndt_data_delete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_ident'], ['user_table.ident'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ident')
    )
    op.create_table('refresh_token_table',
    sa.Column('ident', sa.UUID(), nullable=False),
    sa.Column('user_ident', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('exp_dt', sa.DateTime(), nullable=False),
    sa.Column('gen_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_ident'], ['user_table.ident'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ident'),
    sa.UniqueConstraint('token')
    )
    op.create_index('refresh_token_ident_idx', 'refresh_token_table', ['ident'], unique=False)
    op.create_index('revoked_idx', 'refresh_token_table', ['revoked'], unique=False)
    op.create_index('token_idx', 'refresh_token_table', ['token'], unique=False)
    op.create_table('user_group_table',
    sa.Column('ident', sa.UUID(), nullable=False),
    sa.Column('user_ident', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_ident'], ['user_table.ident'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ident')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group_table')
    op.drop_index('token_idx', table_name='refresh_token_table')
    op.drop_index('revoked_idx', table_name='refresh_token_table')
    op.drop_index('refresh_token_ident_idx', table_name='refresh_token_table')
    op.drop_table('refresh_token_table')
    op.drop_table('permission_table')
    op.drop_index('user_ident_idx', table_name='user_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###
